name: TF FMT check

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Setup Terraform
      - uses: hashicorp/setup-terraform@v1
        name: Terraform Initialize
      - run: terraform init
        name: Terraform Format
      - run: terraform fmt -recursive