name: TF FMT check

on:
  pull_request:
    branches: ["main"]

jobs:
  tf_fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Initialize
        run: terraform init
        working-directory: ./src/terraform

      - name: Terraform Format
        run: terraform fmt -recursive
        working-directory: ./src/terraform