name: TF check

on:
  pull_request:
    branches: ["main"]

jobs:
  tf_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Initialize
        run: terraform init
        working-directory: ./src/terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./src/terraform